18 add feature to edit aws schedulers
getapper/generator-g-next pull request #19
Opened 2023-09-22 05:46 UTC by Clappers001

Added aws-update-scheduler command, now is possible  to update  status,  invocation rate and endpointURL of an existing aws-scheduler.

2023-09-29 07:02 UTC, TheGrinch00 requested changes
Oltre alle modifiche che ti ho segnalato lo renderei più "safe" in generale. Nella parte di writing andrei a controllare ogni cosa, per esempio che `responseSchedule` abbia avuto successo e che abbia ritrovato uno schedule con lo stesso nome richiesto, oppure che il possibile nuovo Status sia effettivamente diverso dal precedente e così via

2023-09-29 07:02 UTC, TheGrinch00 commented on generators/aws-scheduler/index.js
> +      ),
Mettiamo un commento per spiegare a cosa servono questi altri parametri 😊

2023-09-29 07:02 UTC, TheGrinch00 commented on generators/aws-scheduler/index.js
> +      },
Qui come mai hai aggiunto questi due parametri?

2023-09-29 07:02 UTC, TheGrinch00 commented on generators/aws-update-schedule/index.js
> +    });
Più che controllare il secondo elemento dopo il trattino, controllerei se ```indexOf(`genyg-${projectName}`) === 0```, cioè se il nome dello schedule inizia con "genyg-[progetto]"

2023-09-29 07:02 UTC, TheGrinch00 commented on generators/aws-update-schedule/index.js
> +
Prima di iniziare con le domande, controllerei se esista almeno uno schedule da modificare, nel qual caso mostriamo un messaggio e usciamo dal generatore

2023-09-29 07:02 UTC, TheGrinch00 commented on generators/aws-update-schedule/index.js
> +    this.answers = answers;
Qui farei una leggera modifica: invece di chiedere tutte le intenzioni e poi tutti i nuovi valori farei "Vuoi modificare lo status?" "Sì" --> "Qual è il nuovo status?" ecc...

2023-09-29 08:46 UTC, Clappers001 commented
> Oltre alle modifiche che ti ho segnalato lo renderei più "safe" in generale. Nella parte di writing andrei a controllare ogni cosa, per esempio che `responseSchedule` abbia avuto successo e che abbia ritrovato uno schedule con lo stesso nome richiesto, oppure che il possibile nuovo Status sia effettivamente diverso dal precedente e così via


nel caso di responseSchedule, viene già richiesta unicamente la schedule che abbia come name la schedule selezionata durante la fase di prompting, sarebbe un controllo un po ridondante, lo metto comunque?

2023-10-05 12:05 UTC, TheGrinch00 requested changes
Ok, molto meglio, stiamo andando nella giusta direzione 😊 Mi sono venute in mente giusto un paio di migliorie oltre a quelle segnalate:

1. Sarebbe utile se quando mi chiede di modificare lo status, il generatore mi dicesse qual è lo stato attuale dello schedule. Stessa cosa quando mi chiede se voglio modificare l'endpoint oppure la frequenza di invocazione.
2. Includerei la possibilità di poter modificare anche il metodo HTTP dell'API Destination, quindi magari suddividere quella domanda come segue: "Vuoi modificare l'API?" --> "Vuoi modificare l'URL?" --> "Vuoi modificare il metodo HTTP?" Sempre mostrando i dati attuali

2023-10-05 12:05 UTC, TheGrinch00 commented on generators/aws-update-schedule/index.js
> +    }
Mi ero completamente dimenticato dell'esistenza delle RegExp 😅 Questo campo validiamolo con questa:

`/^\d+\s(hours|minutes|days)$/.test(invocationRate)`

Non so come sei messo con le regex ma ti spiego un attimo il significato di questa:

Le RegExp si definiscono mettendole in mezzo a due slash (quelli che normalmente usiamo per i commenti nel codice).

- Il primo elemento `\d` vuol dire "Cerca una cifra" (d sta per "digit")
- Subito dopo abbiamo un `+` che significa "Il simbolo prima deve essere trovato una o più volte", quindi trova numeri a una cifra, due cifre e così via per gestire casi come per esempio il numero 22 o 524.
- Il terzo elemento `\s` va a matchare un qualunque carattere di spaziatura
- L'ultima parte tra parentesi rappresenta un gruppo di opzioni. Nel nostro caso appunto `"minutes" || "hours" || "days"`
- Come ultima cosa, abbiamo all'inizio e alla fine i caratteri `^` e `$` che rappresentano l'inizio e la fine della stringa. Senza quei caratteri, la regex darebbe come buona anche qualcosa del tipo `"qualcosa prima che non mi interessa 20 minutes altra roba strana"`

Questo controllo facciamolo anche nella creazione dello schedule

2023-10-05 12:05 UTC, TheGrinch00 commented on generators/aws-scheduler/index.js
> +      this.destinationPath(`./src/endpoints/${endpointFolderName}/index.ts`),
Io resterei sul template che viene utilizzato già nel generatore delle API perché se un giorno lo modifichiamo  almeno non dobbiamo cercare eventuali copie negli altri generatori

2023-10-20 09:48 UTC, antoniogiordano requested changes
@Clappers001 intanto che testo il tutto, puoi aggiornare il README con i nuovi comandi introdotti? Grazie!

2023-11-08 18:23 UTC, antoniogiordano approved these changes

2023-11-08 18:24 UTC, merged